### ISSUE TITLE
Internal statistics and total polling time?

### ISSUE THREAD

**Issue by pavleec** [toni-moreno/snmpcollector#171]
Hi,

Can you describe shortly what the following statistcs actually mean?
`gc.pause_per_second`
`gc.pause_per_interval`
`gc.gc_per_second`
`gc.gc_per_interval`
Is it possible to calculate the total polling time based on that?
Thanks in advance

**Comment by toni-moreno** [comment]
Hi  @pavleec these metrics are relate to the Garbage Collection on the go virtual machine. these two also has computed twice , one for the complete time pase and number of gc's on one gather cycle xxx_per_interval (set on the config.toml selfmon.freq parameter) and also normalized per seconds  xxx_per_second.

You can see a more  detailed description for all these metrics here (https://golang.org/pkg/runtime/#MemStats).

About total polling time. We are already sending polling time (the complete gather for all measurements on each cycle) for each device to the influxdb backend.

I think it has not sense the sum of times for all devices on the agent , because of concurrency. 

What exactly do you need and why?

**Comment by toni-moreno** [comment]
Hi @pavleec I will close this issue , if you have any other related question please reopen it.
