### ISSUE TITLE
[Question] Issue with BGP OID

### ISSUE THREAD

**Issue by Smenon10** [toni-moreno/snmpcollector#189]
Hey guys me again.

This is more of a question and if it's even possible to make it work.

I have the following influx measurement group

![bgp1](https://cloud.githubusercontent.com/assets/27831991/25351757/abda1a24-28f7-11e7-97d4-122681186557.PNG)

following SNMP metrics

![bgp2](https://cloud.githubusercontent.com/assets/27831991/25351773/b5a0cd00-28f7-11e7-8542-282ba788546c.PNG)

the results from runtime

![bgp3](https://cloud.githubusercontent.com/assets/27831991/25351811/ce977ac0-28f7-11e7-8e82-0131a74f25d1.PNG)

Now the issue. as you can see the BGP status metric works fine (6 = BGP is up) but prefix list is not working. 

From an snmpwalk (hiding IP address, xx = IP address)

.1.3.6.1.2.1.15.3.1.7

SNMPv2-SMI::mib-2.15.3.1.7.xx.xxx.xx.xx = IpAddress: xx.xx.xx.xx

so the OID above ends with a dynamic address and creates a index based on this (this works fine)

from an SNMP walk on the bgp prefix OID

.1.3.6.1.4.1.9.9.187.1.2.4.1.1
SNMPv2-SMI::enterprises.9.9.187.1.2.4.1.1.xx.xxx.xx.xx.1.1 = Counter32: 632031

for some reason, the OID adds a 1.1 at the end of the IP address and hence why the snmp metric isn't retrieving anything. 

So the question, is there a way I can add a 1.1 to get this to work?

Thanks

**Comment by toni-moreno** [comment]
Hi @Smenon10  , first of all I would like recommend use $IDX1 instead of  ${IDX1|ALL|STRING} is simpler and code runs faster. I also recommend the cooked COUNTER32 instead of the Original Counter32, it will send the read amount of quantity over time.

After seeing your config I'm pretty sure your are mixing 2 different snmp tables.

* bgppeer_status belongs to  bgpPeerEntry table (1.3.6.1.2.1.15.3.1)  [http://www.oidview.com/mibs/9/CISCO-BGP4-MIB.html] 

* bgp_prefix_received belongs to the table cbgpPeerAddrFamilyPrefixEntry (1.3.6.1.4.1.9.9.187.1.2.4.1) [http://www.oidview.com/mibs/0/BGP4-MIB.html].

Both tables has indexes but you can not mix them in the same measurement because of  indexes can be different.

Can you review them please?

**Comment by Smenon10** [comment]
That clarifies my issues. Thanks!

**Comment by Smenon10** [comment]
I'm going to reopen because even after doing what was suggest with the index, the data is still missing due to the same reason.

![bgp5](https://cloud.githubusercontent.com/assets/27831991/25400617/2490fab8-29c1-11e7-821b-a91b39ea1e5a.PNG)
![bgp4](https://cloud.githubusercontent.com/assets/27831991/25400619/2788748a-29c1-11e7-8def-9b68e6024321.PNG)
![bgp6](https://cloud.githubusercontent.com/assets/27831991/25400629/2aae3f00-29c1-11e7-8512-75830b03a3f6.PNG)

the bgp_prefixtest OID -> SNMPv2-SMI::enterprises.9.9.187.1.2.8.1.1.1.4.xx.xxx.xx.xx.1.1 = Counter32: 632210

It still adds a .1.1 at the end of the OID (which ends with an ip address)

**Comment by toni-moreno** [comment]
I'm still seeing the two metrics  on the same measurement and you can't mix them !

You should create 2 different measurements, each one with its metric and ech one has its own index and will be different.

**Comment by Smenon10** [comment]
Understood, I thought I could created 1 measurement with all 3 OID but if the indexes arent the same then it doesnt work!
Thanks for the help.
