### ISSUE TITLE
Unnecessary Field - FilterName under /api/cfg/measfilter

### ISSUE THREAD

**Issue by tardoe** [toni-moreno/snmpcollector#205]
As far as I can see, the ID and the FilterName are the same and the name isn't used in the API except for the filters table.

**Comment by sbengo** [comment]
Hi @tardoe 

Each defined Measurement Filter needs a FilterName in order to know the source of it and the filter behaivour. Those sources can be: `OIDConditions`, `CustomFilter` or `file` and are set on `FType` field.

As an example, in case of  `FType: OIDCondition` the `FilterName` is the `OIDCondition` `ID` which the filter is related with:
````
Description:"Test Filter with OIDCondition"
FType:"OIDCondition"
FilterName:"ifMib_ifStatus_up"
ID:"TEST"
IDMeasurementCfg:"myMeasurement"
````
In case of `FType: CustomFilters`, the `FilterName` must  contain the `ID` of the CustomFilter:
````
Description:"333"
EnableAlias:true
FType:"CustomFilter"
FilterName:"213"
ID:"test"
IDMeasurementCfg:"linux_cpu"
````

**Comment by sbengo** [comment]
Hi @tardoe , do you have any more question?
