### ISSUE TITLE
[Feature Request] Regex value on Measurement Tag Format

### ISSUE THREAD

**Issue by sbengo** [toni-moreno/snmpcollector#226]
Hi, it would be awesome to have a `Regex` transformation on Measurement TagFormat definition.
It would allow the user to extract a part of the returned value on indexed Measurements. 

As a proposal, it could be:
`${VAR|REGEX[EXPRESSION]|STRING}`

As an example, some we discovered that some interfaces of a product had the prefix and suffix and the real interface  name on the middle:

`Some Suffix 'eth0' interface`
`Some Suffix 'eth1' interface`
`Some Suffix 'eth3' interface`

This new option would allow to get only the value, setting the TagFormat as:
`${IDX1|REGEX['(.*?)']|STRING}` would generate:

`Some Suffix 'eth0' interface --> eth0 `
`Some Suffix 'eth1' interface --> eth1`
`Some Suffix 'eth3' interface --> eth3`

**Comment by toni-moreno** [comment]
Finally we can use REGEX as a Search/Substitution SELECTOR.

The syntax will be.

`${VAR|REGEX/regex-expresion/substitution-expresion/|STRING}`

* __regex-expresion__: could be any valid [golang based regular expressions](https://github.com/google/re2/wiki/Syntax). These regular expressions should have defined [capturing groups](http://www.regular-expressions.info/refcapture.htm) 
NOTE:  __we can not use the "|" character__ because of this character would alter the `${VAR|SELECTOR|TRANSFORMATOR}` struct.  ( In the future would should improve syntax to avoid this limitation).

* __substitution-expression__: any string containing valid [back references](http://www.regular-expressions.info/refcapture.html) ie "\1, \2, \3, ..... etc", for previously defined capturing groups
