### ISSUE TITLE
[Bug] Webui very very slow (scalability problem ? ) 

### ISSUE THREAD

**Issue by bk-khaled** [toni-moreno/snmpcollector#296]
- What SnmpCollector version are you using?
**v0.7.4**
- What OS are you running snmpcollector on?
**Ubuntu 16.04.3 LTS**
-Memory of the machine where snmpCOllector is running? 
**it was 4Go before, we change it to 16Go to check if the latency was a memory problem**
-Number of Devices to collect Metrics from : 
**1500**
- What did you do?
**Using snmpcOllector via the Webui ,trying to see the Runtime of a device** 
- What was the expected result?
**a quick view of the metrics for the concerned device**
- What happened instead?
**a long long time before having a visual of the page and it's not the first time, it happens a lot !**
**it's a recurrent problem, even after we change the RAM from 4go to 16go, it get a little bit faster but not enough **

**Comment by toni-moreno** [comment]
Hi @bk-khaled The SnmpCollector in as a collector engine has been designed to be scalable enough. 

As an extra feature has  a runtime view where you can see current gathered data ( mainly to check and debug  that you are getting the values you expect , especially on metric templating  design time, and not for  to access data or visualise them very often) 

When you are trying to see the details of each device, web-ui is blocked until a complete gather cycle has been completed, because of you are acceding directly to the internal data structs, in order to show correct values is mandatory a way to block the data access until a cycle is done. You can see more detailed explanation on this issue here (https://github.com/toni-moreno/snmpcollector/issues/218#issuecomment-304427154) 

Could you tell me how many measurements/metrics are you gathering on  your "slow" device and how log is taking in complete a gather cycle , what period has configured?

Could you show me a screenshot of the main runtime view ordered by gathered time (max to min)? sometime very big times are symptom for some gathering problem on the device.

I hope this could explain you the snmpcollector behaviour

**Comment by bk-khaled** [comment]
Hi @toni-moreno, thank's a lot for this detailled answer ! 

We now understand better the goal of the runtime view.

It figured it out that you'r right about it , we have some slow devices that collect in 4.7 minutes ! and we have a cycle of 5 minutes to gather, so the window where the collect is ended and the Runtime is no more frozen before the next cycle is very short that was the reason why. 

We are collecting about 25 metrics each 5 minutes from 1500 devices.

i can understand why it's frozen now but , can we find another way to at least, see the previous result of the collect while he's gathering the new one ? something like you suggested in the issue #218 :
"This is not strictly true. Indeed exist a way to avoid this contentions, and consist on have a duplicate set of data ( accessible while updating the original set of data) continuously in memory and updated on each gathering process."

**Comment by toni-moreno** [comment]
Hi @bk-khaled I think that 4.7 minutes to take only 25 metrics are to much. What kind of devices are you polling? how long takes these metrics if you  get data directly with the net-nsnmp snmpget/ snmpwalk  commands ?

**Comment by toni-moreno** [comment]
Hi @bk-khaled about duplicate the set of data to avoid contention is a feature I don't like. The aim of this project is build a fast easy and light snmp collecting metrics agent, if we let duplicate data the agent will spend twice the needed memory.

Anyway you should add a new feature request if you think is important for you , if a lot of people believe they need also and mark with +1  we will be able to add the feature.

**Comment by toni-moreno** [comment]
Hi @bk-khaled .

Our SnmpCollector by default does 1 snmp connection for each defined measurement and does conncurrent queries over its N established snmp connections ( N = # measurements) . 

 Sometimes some devices has not good support for concurrent snmpqueries  on the same device.  Can you test again disabling concurrent gathering? and compare gathering duration  time?

![image](https://user-images.githubusercontent.com/5883405/34297595-539790fe-e719-11e7-9596-b3cdc9bad460.png)

**Comment by bk-khaled** [comment]
Hi @toni-moreno ! We thaugh it could be about the Concurrent Gather so we already tried and it wasn't the problem. On a healthy device from the same vendor, the diffrence of time between a concurrent gather et and normal one is 0.1 min (4.6 min vs 4.7min) and on a troubled device also from the same vendor, the diffrence of time it's 0.3min (10.7min vs 11min) . 
I guess thus devices have some problems to be that slow because the devices from others vendor are faster ( the gather cycle it's in secondes).

**Comment by toni-moreno** [comment]
Hi @bk-khaled  I  will close this issue, since there is no way to improve your gather time. We have added in last commits a Spinner message "waiting gathering cycle.." ( or something similar) on the runtime when you click the detailed view of this device and it is already gathering data... 

Feel free to open new issues when you need.
