### ISSUE TITLE
rates & utilization & spelling [question]

### ISSUE THREAD

**Issue by jensenja** [toni-moreno/snmpcollector#305]
Hi,

I've started playing with snmpcollector and I'm a fan of its interface and power. Great work so far. I have some questions. Sorry if putting them all in one post is poor etiquette, but I figure it would be nicer on your collective inboxes to file one issue instead of separate ones.

I'm coming from the snmpdata->Graphite world, so there's some aspects that are confusing me. When I collected snmp stats and dumped them into Graphite, I took advantage of Graphite's built-in functions for calculating rates eg. `scale(scaleToSeconds(nonNegativeDerivative(<SERIES>), 1),8)` to take the series (say ifHCInOctets), run the nonNegativeDerivative() function on it to generate the rate, then run the scaleToSeconds() function on it get the per-second rate, then scale it by 8 to get bits per second rather than bytes per second.

I'm curious to what the equivalent action is in snmpcollector to achieve the same thing. If I were to just use the SMI Counter64 Data Source type, is it especially difficult to tell InfluxDB to calculate rates via a similar function/transformation?

And as such - is that why snmpcollector is doing this work for us with the COUNTER64 "cooked" type? (and I'm assuming "cooked" here means that snmpcollector is munging the data somehow before inserting into InfluxDB?).

To that end - when should the COUNTERXX data source type actually be used? What does "unknown range or buggy counter" actually mean? Is this a data source that's designed to detect wrap-around events? Do the cooked COUNTER32/COUNTER64 data sources already handle wrap-around events?

My next question has to do with calculating input/output utilization according to your wiki. While I'm not polling Cisco Catalyst devices, the numbers I am getting back appear to be wildly inaccurate. Are we sure that the expression in the wiki (`(ifHCInOctets/ifHighSpeed) * 800`) is the right formula to calculate the interface utilization? Assuming a 60second poll rate, I've always known the formula to be:

    ( ( ( ( t2.ifHCInOctets - t1.ifHCInOctets ) * 8 ) / 60 ) / ifHighSpeed )

Is there a way in snmpcollector to evaluate returned values from those taken at the current time interval to the ones at the last time interval? That should yield accurate rates of utilization.

Last but not least - there are quite a few spelling/grammar mistakes in parts of the code - ie `pooling` in logs when it should be `polling`, `cicle` as opposed to `cycle`. Would a PR be cool to correct these and others as I find them?

Thanks for taking the time to read this.

**Comment by jensenja** [comment]
Ok, I think I figured out why the utilization numbers are inaccurate. According to the code, you're already essentially doing the proper calculation when the rate is obtained:

    (currentValue - lastValue) / elapsed_time

the issue is that we're using ifHighSpeed, which expresses the bandwidth of an interface in units of 1 million bits per second. So this is actually the formula that's needed in order to get accurate utilization numbers:

    ( ( ifHCInOctets * 8 ) / ( ifHighSpeed * 1000000 ) ) * 100
    ( ( ifHCOutOctets * 8 ) / ( ifHighSpeed * 1000000 ) ) * 100

**Comment by sbengo** [comment]
Hello @jensenja !

I will try to answer all your questions:

### Counter32, 64 vs COUNTER32, 64, XX

When we started to work with SNMP, we realized that almost all collected metrics were defined as counters. As you commented on your explanation, to see the value would need several transformations generating an unnecessary on data backend.

In order to avoid that, we decided to create a new type of `DataSrcType` called `COUNTERS` with the following behaivour: it calculates the currentValue - lastValue to get the real value (similar to difference aggregator).
Note that on the first polling, the SNMPCollector won't send any value and it will store it for the next evaluation.

DataSrcType|time 0 | time 1 | time 2
-----------|-------|--------|-------|
Counter32,64|100 | 125 | 129
COUNTER32,64|--|25 | 4

As the metric is defined as a counter, it is expected to have an incremental behaviour.
In some devices or interfaces (i.e: mgmt0) the counter can be reset before it arrives at its maximum value or have a buggy behaviour (decrease at some point).
In those cases the `currentValue` is less than `lastValue`  and its evaluation would produce a incorrect value of maximum of floats value. For those cases, we created the `COUNTERXX`: it will send the `lastValue` , and it will keep storing it for the next points.

On this kind of metric type, it has an extra configuration to calculate also the rate. If the configuration is set to `true` it will divide the result by the `elapsed_time`.

Assuming elapsed exactly 1m:

DataSrcType|time 0 | time 1 | time 2
-----------|-------|--------|-------|
COUNTER32,64,XX|--|25/60 | 4/60

### Input/Output Utilisation

Sorry, you  are totally right, I have updated the Wiki with the correct formula! 
When we started with this project we were using the ifSpeed (bits unit) metric since not all the devices we were polling had the HC version of counters.

The formula that you attached is correct if you had set up the `ifHCInOctets` and `ifHCOutOctets` with the `GetRate = true` property

-----

About your question:

> Is there a way in snmpcollector to evaluate returned values from those taken at the current time interval to the ones at the last time interval? That should yield accurate rates of utilization.

Hope it is resolved with the above explanation

### Spelling & typos

We are quite ashamed! :no_mouth: We will try to do an effort to improve our spelling!
Feel free to make a PR to fix it!

Thank you,
Greetings!

**Comment by jensenja** [comment]
Hi @sbengo 

Thanks for taking the time to respond, and thank you very much for the detailed explanations. I'll start on a PR to fix the typos as soon as I get some free time over the next couple days. No need to be ashamed!

Regarding the rate calculations - that makes perfect sense, and I think it's awesome that these optimizations were made in order to reduce the load on Influx! My final question has to do with graphing these values in a tool like Grafana.

The utilization numbers were very easy to do, since (I believe) all I needed to do was use the `mean()` function, ie:

    SELECT mean("InputUtilization") FROM "ifMIB_basics" WHERE ("device" = 'some_switch' AND "ifName" = 'LAG2') AND $timeFilter GROUP BY time($__interval) fill(null)

Does that look good? Would you guys recommend this approach?

But for other stats like octets/bcast/unicast/etc (that we have getRate = true set on) we don't need to use a `derivative()` or `non_negative_derivative()` function on the series - so is the accepted way to just use `mean()` again here? eg:

    SELECT mean("ifHCInOctets")  * 8 FROM "ifMIB_basics" WHERE ("device" = 'some_switch' AND "ifName" = 'ethernet2/22') AND $timeFilter GROUP BY time($__interval) fill(null)

Thanks again!!!

**Comment by sbengo** [comment]
Hi @jensenja !

About the aggregate of `Input Utilization`:
I think it can be defined depending on the desired behaviour and the group by clause, but normally we  use "mean" or "max".

On some devices, your desired behaviour is that your occupation must be as higher as the interface can so, the problem would appear if your interface occupation is very low. In this case I would set up to show the "minimum" occupation.
In other cases it can be set with `max` if you know that at 80% it will start to decrease the performance of your device.

About the `ifHCInOctets`, 2 comments:

1. If it is set up as rate, use the mean function, yes!
2. If you want to save all the `octets` metrics as bits, you configure your metric with `Scale = 8` property. Note that you have to change the Input/Output utilisation formula!

Thanks,
Greetings!

**Comment by jensenja** [comment]
Hi @sbengo 

Thank you very much! I'll go ahead and close this now, as all my questions have been answered. Look for a PR from me soon. Thanks again!!!
