### ISSUE TITLE
[Feature request] - Base OID that returns more than one result per entry

### ISSUE THREAD

**Issue by SteveRodrigue** [toni-moreno/snmpcollector#322]
I'm working on IP SLA monitoring and I don't know how I can add my data into SNMPcollector.

Here is the table I'm working on:
rttMonStatsCollectEntry (1.3.6.1.4.1.9.9.42.1.3.2.1)

Within that table, there is one particular information I want to add to SNMPcollector:
rttMonStatsCollectTimeouts (1.3.6.1.4.1.9.9.42.1.3.2.1.2)

When I query my router for that particular information, here is the output I receive:

`snmpwalk -v2c -c xxxxxx hostname .1.3.6.1.4.1.9.9.42.1.3.2.1.2`
`[...]`
`SNMPv2-SMI::enterprises.9.9.42.1.3.2.1.2.17.553970686.1.1 = INTEGER: 19`
`SNMPv2-SMI::enterprises.9.9.42.1.3.2.1.2.17.554330686.1.1 = INTEGER: 3`
`SNMPv2-SMI::enterprises.9.9.42.1.3.2.1.2.18.553760624.1.1 = INTEGER: 0`
`SNMPv2-SMI::enterprises.9.9.42.1.3.2.1.2.18.554120624.1.1 = INTEGER: 0`
`[...]`

As you can see, the output returns 2 entries per IP SLA probe (17 and 18 are the configured IP SLA probe in the router).

There is at least 2 problem:
- I don't know how/why the number following the index 17/18 is generated? 553970686, 554330686. Any advice/tips on how I could find out how these are generated?
- Only the second entry is interesting to us (INTEGER: 3), which is the number of timeout for a particular probe.

I look at the WiKi and I found that MULTISTRINGPARSER may help me collect the information, but I'm not sure.

**Comment by sbengo** [comment]
Hello @SteveRodrigue 

I have been reading about it and it seems to be a very complicated and interesting SNMP table!

As I could understand, the schema is the following according to documentation:
**This is what I supposed after reading the documentation and without testing it. THE FOLLOWING EXPLANATION COULD BE TOTALLY WRONG**

http://cric.grenoble.cnrs.fr/Administrateurs/Outils/MIBS/?oid=1.3.6.1.4.1.9.9.42.1.3.1.1

> The statistics capture table has five indices.  Each described as follows:
> - *IX1* - The first index correlates its entries to a conceptual RTT control row via the rttMonCtrlAdminIndex object.
> -  *IX2* The second index is a rollover group and it uniquely identifies a 60 minute group. (The rttMonStatsCaptureStartTimeIndex object is used to make this value unique.)
> -  *IX3* When the RttMonRttType is 'pathEcho', the third index uniquely identifies the paths in a 
> statistics period.  (The period is 60 minutes.)  A path will be created for each unique path through the network.  Note:  A path that does not contain the target is considered a different path than one which uses the exact same path, but does contain the target.  For all other values of RttMonRttType this index will be one.
> -  *IX4* When the RttMonRttType is 'pathEcho', the fourth index uniquely identifies the hops in each path, as grouped by the third index.  This index does imply the order of the hops along the path to a target.  For all other values of RttMonRttType this index will be one.
> - *IX5*  The fifth index uniquely creates a statistical distribution bucket.

Using your example:
````
IX1 - 17
IX2 - [553970686, 553970686] - (2 possible values (read the following point))
IX3 - 1 - Means that RttMonRttType is not pathEcho
IX4 - 1 - Means that RttMonRttType is not pathEcho
IX5 - unset - (??) I think it is unset on StatsCollect table
````

According to documentation, the `IX2` are the number of milliseconds that [rttMonStatsCaptureStartTimeIndex](http://cric.grenoble.cnrs.fr/Administrateurs/Outils/MIBS/?oid=1.3.6.1.4.1.9.9.42.1.3.1.1.1) started to capture data.

The number of entries are defined by the following OID [rttMonStatisticsAdminNumHourGroups](http://cric.grenoble.cnrs.fr/Administrateurs/Outils/MIBS/?oid=1.3.6.1.4.1.9.9.42.1.2.7.1.1). By default this value is set up on __2 hours__, so it means 2 time buckets of 60 minutes = 2 entries.

According to that, it will be creating 2 entries every 60 minutes and rolling over with new indexes with the desired values.
In your example, you are storing 2 timebuckets of 60 min in each entry: `[553970686,554330686]`

## Required configurations

With the above explanations it's is possible to collect metrics using an `Indexed Measurement` with the same `IndexOID` as metric `BaseOID` but with several needs:

- A variable index means infinite InfluxDB series. In this case a special `IndexTagFormat` is needed on measurement definition.
You can follow [IndexTag format definition](https://github.com/toni-moreno/snmpcollector/wiki/Component:-Measurements#indextagformat-definition) to parse the indexes but note that if you have always 2 timebuckets and, i.e you only get the IX1 (17 or 18), you would be trying to insert the same serie with 2 values. 
Example, __the following `IndexTagFormat` would produce the same Tag and would send a duplicated serie/point to InfluxDB. It means that only 1 of both values would be inserted on DB__.
````
IndexTagFormat = ${IDX1|DOT[2:2]|STRING}

.17.553970686.1.1 = INTEGER: 19 --> Index = 17, Value  = 19
.17.554330686.1.1 = INTEGER: 3 --> Index = 17, Value = 3
````

- With the above, I think that you need to set up only 1 time bucket (rttMonStatisticsAdminNumHourGroups) to __generate 1 static tag for every IX1__

- As it seems that values have an incremental behaviour during the 60 minutes timebucket, if you set up a polling time less than 60 min you would have to use the `COUNTERXX` as `DataSrcType` in order to compute the real values (difference between them but with protection if a new timebucket is created)

- As it is creating (rolling over) an index every 60 minutes, polling it at different times would have different indexes.
It means that when the SNMPCollector would try to math to match the indexes with the metric it can mismatch if the index frequency refresh is different than the started time of IP SLA prove. In order to avoid mismatching indexes __the `FilterFreq` device parameter would have to set up as the same as the `Freq` polling time__.

In the following example will be getting errors for 30min:

````
Polling time = 1m
FilterFreq = 60 = 60 * 1m = 60m

Device refresh index timebucket IX2 at 0:00:00 with value 12346
Device starts polling at 0:30:00
Getting indexes: IX2 at 0:30:00 = 123456
Device polls at 0:31:00 --> OK, the index match with stored IX1 = 123456

Device refresh index timebucket IX2 at 01:0:00 with value 123789
Device polls at 1:01:00 --> NOOK, the index mismatch with stored IX2 = 123456
Device polls at 1:02:00 --> NOOK, the index mismatch with stored IX2 = 123456
...
Getting indexes: IX2 at 1:30:00 = 123789
Device polls at 1:30:00 --> OK, the index match with stored IX2 = 123456

````

**Comment by SteveRodrigue** [comment]
Wow!  Quite an extensive explanation.

I will try to collect in a simple fashion first, with what you've suggested. I'm not sure if the "overwrite" will have an impact, because our goal is to see if this counter is not equal to 0.

Actually, this make a lot of sense to keep to "rolling" counters for IP SLA, but I wished their would have existed a simpler counter that would only be the "sum" of all timeouts/errors. It is not the case.

**Comment by SteveRodrigue** [comment]
I just added the metric.

I've use this: ${IDX1|DOT[0:0]|STRING}

As you said, SNMPcollector would "overwrite" the data, but I don't mind much. I'll check in the next days/weeks how the collected information looks like, then I may tweak/revisit the configuration.

Based on my original sample, here is what I have in the DB:
17 = 3
18 = 0

**Comment by sbengo** [comment]
Hi @SteveRodrigue !

We are glad about you could define your measurement!
Can we close this issue / FR?

Thanks,
Regards
