### ISSUE TITLE
[Bug] Snmpcollector stuck in restart loop

### ISSUE THREAD

**Issue by hoosee** [toni-moreno/snmpcollector#338]
Hi,

Just to start off, would be great to have a discussion board somewhere where other people than just the developer could give help. Most likely my problem is just a misunderstanding in configuration which causes things to break.

I'm trying to create just simple measurements to collect data from IF-MIB. I have been testing with two boxes; one home router (which only supports 32-bit counters) and a raspberry running rasbian (using 64bit counters). I've created the measurements and tests seem to go fine as far as I can tell. However when I enable the measurements, snmpcollector starts restarting itself and only way out is to stop the service, delete the measurement from the database and start the service again.

-Version v0.7.6
-Linux Mint 18.2 Sonya

[panic.log](https://github.com/toni-moreno/snmpcollector/files/1879467/panic.log)
[snmpdebug_kermapurkki_ifMIB.log](https://github.com/toni-moreno/snmpcollector/files/1879476/snmpdebug_kermapurkki_ifMIB.log)
![snmp metrics](https://user-images.githubusercontent.com/37834057/38360639-6a754d0a-38d3-11e8-8f78-c4290ae2d9e6.png)
![influx_measurements](https://user-images.githubusercontent.com/37834057/38360641-6d3295de-38d3-11e8-81ac-ad1ae8f7303a.PNG)

**Comment by sbengo** [comment]
Hi  @hoosee , thanks for reporting this.

I have been reviewing your metric & measurement definitions and I think I found the casue of panic:

You have defined the metric `ifOperStatus` as a `BIT` metric and, according to [info](http://www.alvestrand.no/objectid/1.3.6.1.2.1.2.2.1.8.html), it must be defined as an `INTEGER`.

Can you change your metric type and set it to `INTEGER` and test it again?

Note that on the non-released version (yet), there is a new type called `ENUM` that allows map and save the values as a `STRING`. If you  want to  test it, you can build  it from source and follow instructions expllained on the [wiki](https://github.com/toni-moreno/snmpcollector/wiki/Component:-SNMP-Metrics#about-enum-metric-type)

Thanks,
Regards

**Comment by hoosee** [comment]
Thanks, it was really something so simple *blush*

Now I'm getting some nice fancy graphs:
![image](https://user-images.githubusercontent.com/37834057/38390756-e972c1c6-392a-11e8-8f2b-436d442e6d99.png)

(top graph is collected by Telegraf, bottom by snmpcollector since I wanted to see if I get the same results)

Next stop is trying this at work with some real network equipment ;)

(offtopic)
Btw. this is more of feature request / question but wouldn't it be useful if you could set polling rate per metric, not per host? Not every metric needs the same resolution.
(/offtopic)

**Comment by sbengo** [comment]
Hi!
We are glad you could start to retrieve data from your devices!

As I have seen, you have defined your `counter` metrics as type `Counter32` or `Counter64`. We have defined the `COUNTER32` and `COUNTER64` metric types that computes the difference on values (every polling time) in order to avoid the nonNegativeDerivative, and, furthermore, it allows the `GetRate` function to get the rate of the counter. I recommend you to take a look on those metric types.

On your question/fr about polling rate on metric, we had some thoughts about this. We considered that to be able to compare different data or do operations between metrics it must have the same polling period. Furthermore, the idea of SNMPCollector is to make easy as possible to add a new device with already defined its template (measurement groups) based on shared configurations (metrics and measurements have to be only  defined once). Adding poll rate on metrics would be quite hard to maintain.

I have to say but, you can enable different polling period if you duplicate the device with other `ID` and other `Freq`. Note that to send the same tag you have to set the `DeviceTagValue` field as `Host` (ID is unique on configuration db)

Thanks,
Regards!

**Comment by hoosee** [comment]
Thanks for the input.

Actually I was just searching information about Grafana and how to handle the problem with 32bit counters wrapping over and if using those cooked types solves the issue, I'm happy :)

I was also thinking about adding a second device with different poll rate. I guess it's still possible to override the device ID-value so that in influxdb measurements with both poll rates will be with same ID?
