### ISSUE TITLE
Octet string truncated to 10 characters

### ISSUE THREAD

**Issue by AL7DS** [toni-moreno/snmpcollector#341]
Using version 0.7.6
When pulling metrics of type OCTETSTRING from an OID, the result is truncated at 10 characters.
String from OID - "This is a sample string of data"
String as displayed - "This is a "

**Comment by sbengo** [comment]
Hi @AL7DS , thanks for reporting this.

I have tested with `ifDescr - 1.3.6.1.2.1.2.2.1.2` OID and everything looks fine:

**Gathered data**
![image](https://user-images.githubusercontent.com/13196237/38923220-606bc092-42fa-11e8-9f86-dbed275d122d.png)

**Stored data on InfuxDB**
![image](https://user-images.githubusercontent.com/13196237/38923857-cd57d064-42fb-11e8-8b42-247d79e0b9a1.png)

In order to diagnose your issue, can you provide more info?
- Full metric definition (OID, options)
- Query result from TestConnection modal
- Measurement definition
- Runtime + InfluxDB result

Thanks,
Regards!
