### ISSUE TITLE
[Question] SNMP results written to file in influxdb format (like telegraf)

### ISSUE THREAD

**Issue by jjess** [toni-moreno/snmpcollector#408]
I'm trying to find a quick way to speed up snmp queries to ingest in influxdb. Telegraf seems to be not quick enough. But I need to write the results to file, in the same way Telegram is able to do, with the influxdb format (for later ingestion with 'influx -import'), instead of direct ingestion in InfluxDB (due to network connectivity issue).

My question is if snmpcollector could be a good replacement for telegraf to generate those influxdb format files as a result of snmp queries.

Thanks in advance,

Jes

**Comment by sbengo** [comment]
Hi @jjess , actually it is not supported on SNMPCollector. You can change issue name to a FR if you want to or close this and create a new one.

As a workaround (I know its a bit rude due to you need to setup 2 agents) you can set up a Telegraf with an `input/influxdb_listener` in order to make it as a relay, configure SNMPCollector to send it on this listener and finally configure on Telegraf the `output/file` in order to write metrics to your desired file!

Give us some feedback if you achieve it!

Thanks,
Greetings!

**Comment by toni-moreno** [comment]
I will close this issue , feel free to reopen it if needed.
