### ISSUE TITLE
SNMP tables help

### ISSUE THREAD

**Issue by si-meone** [toni-moreno/snmpcollector#413]
Hi I have had success with the software to get single oids.
Really nice work, allows for some really granular config.
I was wondering how would someone use the product to get information out of snmp tables.
e.g. iFtable
I have looked through the wiki/examples but i've got stuck and any help would be appreciated.
Kind Regards

**Comment by toni-moreno** [comment]
Hi @si-meone in order to get table data you should first configure all available/desired data from the table as in example (https://github.com/toni-moreno/snmpcollector/wiki/Example:-Configuring-Cisco-Catalyst-Switch#11-configure-basic-metrics)

 And then you should create a new measurment with all these snmpmetrics , choosing a "Indexed" Measurement (https://github.com/toni-moreno/snmpcollector/wiki/Component:-Measurements#configuration-parameters) On the "GetMode" parameter, as in the example(https://github.com/toni-moreno/snmpcollector/wiki/Example:-Configuring-Cisco-Catalyst-Switch#21-ifmib-measurement), in this configuration you shoud provide the OID which you need to index the table "Index OID" tha will be tagged with the "IndexTag" name.

let me know if you can now get Iftable data with these few instructions.

**Comment by si-meone** [comment]
Hi Toni,
    Great advice - I see , I've badly assumed that it would auto discover if i provided a root oid, I see you have to create  the individual oid entires e.g. ifOperStatus, IfOutOctets in snmp_metrics, then in influx measurements create a ifTable entry and then add them all in as fields. 
Also great extra advice about 'in this configuration you should provide the OID which you need to index, I noticed once in influx I can see now see all the ports under ifTable > portName , what is strange i guess is that is shows all of them and I have to figure for what device. Maybe I need do something extra, I was hoping the only the portNames available for the device would appear instead all of them (some way of filtering). Very happy with how far i've got and it works to some degree, very grateful - much appreciated Tony.

**Comment by si-meone** [comment]
my example is i have a standard pc with eth0 and a switch with ge-0/0/10.0 at the moment I see both instead of only the one available

**Comment by jensenja** [comment]
Hi @si-meone 

In order to solve the problem of differentiating the fields at the device level, when you configure your device under "SNMP Devices", you can set a unique value for the "Id" of the device. In my production environment, I use the hostname of the device itself.

Then, under "Data Settings", choose your "device tag name" (I just use the word `device`) and for the tag value, you can choose either the "Id" (what you set earlier for the Id) or "host" (just the IP address of the device). From this point your InfluxDB series in your configured measurements will have tags associated with the device.

For example, if I set a device `Id` to "core.switch.01" and configure the device tag name as `device` and the device tag value as `Id`, I should have series that would look like this (if my measurement name is `ifMIB_basics`:

```
> show series
...
ifMIB_basics,device=core.switch.01,ifName=ethernet1/8
ifMIB_basics,device=core.switch.01,ifName=ethernet1/9
ifMIB_basics,device=core.switch.01,ifName=ethernet1/10
...
```

At this point you can query Influx (either by hand or using something like Grafana) to narrow down fields returned by device as well as interface, since you've set the Index OID as well as the Index Tag value.

**Comment by si-meone** [comment]
Hi John, Ah I see thanks for the explanation, I see what those fields mean now. I had set those previously.  Looks like  the data looks a certain way in the influxDB using InfluxQL explorer , when I switched to Flux I could change the query to show me interfaces that had measurements for that host. 

from(bucket: "snmp_test/autogen")
  |> range(start: dashboardTime)
  |> filter(fn: (r) => r._measurement == "ifTable")
  |> filter(fn: (r) => r.device == "demo.snmplabs.com")

seems cool. when we exported from telegraf input.snmp in the past the explorer only showed the interfaces available for the that particular device, seems something in influxDB. Not sure is you've seen that [here in this link](https://photos.app.goo.gl/4kBDFo5xpY4Z2G9aA)

**Comment by nasras03** [comment]
I've just recently looked through the one from Telegraf and it probably would be similar . So i think i'm in good shape. Thanks a lot for your help. I noticed you are looking in version 1.0 of  having a 'Automatic OID lookup and form completion from MIB database'. and in the meanwhile we could use https://github.com/topranks/mib2SnmpCol possibly it seems

**Comment by sbengo** [comment]
Hi guys, reading the last comments, can we assume this issue has been resolved so we can close the issue?

Thanks,
Greetings!

**Comment by si-meone** [comment]
Hi All, I’m happy and really appreciated the help.
Kind regards
Simon

Regards
Simon

On 17 Oct 2019, at 7:41 am, sbengo <notifications@github.com> wrote:

﻿

Hi guys, reading the last comments, can we assume this issue has been resolved so we can close the issue?

Thanks,
Greetings!
