### ISSUE TITLE
[Question] How to tag mesurements by interface

### ISSUE THREAD

**Issue by jjess** [toni-moreno/snmpcollector#430]
Hi:

I'm not sure if this is possible and how ,or not. So here it goes my question. I have several devices, with a number of interfaces to monitor (basically traffic). But each interface carries out an special type of service (for example mobile traffic, fixed traffic, signalling). So what I want is to have a TAG associated to all devices and an specific interface of them. At then, if there is 3 types of traffic/service, with 3 interfaces by device, I would like to  have 3 TAGs. The purpose of this is to be able to filter in Grafana by TAG (mobile, fixed, signalling).

If I use "extra tags" what I get is to have all the tags associated to every single device, but I cannot discrimine by interface as well.

So, what do you think? is there a possibility to do this?

Thanks in advance,

Jes

**Comment by jjess** [comment]
Hi:

I've found a solution for this. It consists of creating new Influx Measurements, one per type of traffic, and then bind every single specific interface (OID) with the appropiate Measurement Filter and its specific Measurement. 

So at the end what I have is several influx measurements and in Grafana I'm able to select what type of traffic I want to visualize querying the appropiate index/table. 

I don't know it there is a simpler approach or not. But I couldn't find one based on tags.

BR,

Jes

**Comment by sbengo** [comment]
Hi @jjess , glad to see that you have found a workaround!

In order to try to help you, I'm not sure I have really underestood your usecase:

a) You want 1 tagKey with 3 possible TagValues for each interface:
```
ifName = eth0 | myTypeOfService=mobile| ifHCInOctets = 10
ifName = eth1 | myTypeOfService=signalling | ifHCInOctets = 20
```

b) You want 3 tagKeys with 1 possibel TagValue for each interface:
```
ifName = eth0 | mobile = true | ifHCInOctets = 10
ifName = eth1 | signalling = true | ifHCInOctets = 20
```

I'm not sure how had you done this using spcecific measurements and measurement filters:
- Can you attach some screenshots or examples?
- The type is being retrieved by some OID and its common for all interfaces?

Thanks,
Regards!!!

**Comment by jjess** [comment]
Hi:

Well this issue could be closed, but maybe it could be useful as a new future feature. So let me explain myself in a better (I hope) way.

In my case I have a very big router network, but for one specifi project I'm only considering a small amount of them, and currently the number of interfaces is around 300. Every router has several interfaces, and every interface carries out a different type of traffic.

Example:

Router A

interface0 : mobile traffic
interface1 : fixed traffic
interface2 : signalling

And not all the routers has the same numer of interfaces, or IDs for them. 

It's not as quite simple as the example (I have 12 distinct types of traffic) but for the sake of illustrating the use case....

At the begining I thought it would be as simple as choosing a specific tag for every interface (of the same type), but it seems snmpcollector doesn't permit add tags per interface/OID/measurement filter. 

The purpose of this is to be able to visualize a specific kind of traffic, let's say 'mobile traffic' in Grafana. The idea is to filter out in Grafana by a tag, a tag with a value associated to 'mobile traffic', 'fixed traffic' and so on.

But all the tags I can add in snmpcollector are either read values from a OID (ifName, ifAlias, etc.) or extra_tags added to the device. But I cannot add specific tags per measurement filter.

The workaround is to define different Influx Measurements:

mobile
fixed
signalling

and the create the appropiate measurement filters (against the appropiate OID conditions and interfaces) associated to one of those Influx Measurements.  Then, in Grafana, I can filter the traffic I want to see with queries like:

SELECT whatever
FROM "myretention"."mobile" WHERE  ....

SELECT whatever
FROM "myretention"."fixed" WHERE  ....

But I'm not sure if this is the best approach. Maybe adding a tag by OID Condition or Measurement Filter could be a good idea, or something like that.... in order to be able to build filters.

What do you think? 

Close this issue if you want and best regards,

Jes

**Comment by sbengo** [comment]
Hi @jjess , thanks for the detailed explanation!

As a brief, you have to map each interface from each device in order to generate a custom tag

I can give you 2 approaches as how this can be easier for you to mantain:

1. Using `ifAlias` and `MULTISTRINGPARSER`

As you might know, there is a field on each interface called `ifAlias` and the value can be set by the network manager. I would recommend you and, obviously if you can manage it, to put your desired types in this field. Lets say:

```
Device: router1
Interfaces: interface 1 - ifAlias: <your_old_alias> | <traffic_type>
```
With this configuration you can configure a new metric from OID `ifAlias` as `MULTISTRINGPARSER` and with a simple regex you can be able to generate a new Tag  with your desired values. More info on [`MULTISTRINGPARSER`](https://github.com/toni-moreno/snmpcollector/wiki/Component:-SNMP-Metrics#about-multistringparser-metrics)

2. Using `STRINGEVAL` and `VarCatalog` and `ifName`

As I have explained you on https://github.com/toni-moreno/snmpcollector/issues/428, you can define your `VarCatalog` and can be overriden on each device. Those vars are available on all measurements and metrics, so you can use `STRINGEVAL` to play with them in some way.

I'm not sure if the following would work, but:
You can set different `VarCatalog`, 1 var for each `traffic_type`. The value of those would be overwritten by each device with a list of desired match interfaces. According with your example:

```
Router A
interface0 : mobile traffic
interface1 : fixed traffic
interface2 : signalling
interface3: mobile traffic
---
Var Catalog:
mobile_traffic
fixes_traffic
signalling

RouterA VarCatalo override:
mobile_traffic = interface0;interface3
fixed_traffic = interface1
signalling = interface2
```

Then you can configure in your measurement, 1 metric for each `traffic_type` and as `STRINGEVAL` to set up your desired tag. The behaviour must be: compare for each `traffic_type` if the retrieved interface name (`ifName`) matches on the overriden varcatalog:

https://github.com/Knetic/govaluate/blob/master/MANUAL.md#regex-comparators--
https://github.com/Knetic/govaluate/blob/master/MANUAL.md#ternary-true-

```
Field: traffic_type
IsTag : true
DatsrcType: STRINGEVAL

ExtraData:
ifAlias =~ mobile_traffic ? "mobile_traffic"
```
This would let you control those vars from the device and be able to load them without restarting or reloading config (as it is device config at all can be done on deploy operations)

Can you test it and give us some feedback?

Thanks,
Regards!!!

**Comment by jjess** [comment]
Hi:

Thanks for the detailed response. But one question, you say:

"there is a field on each interface called ifAlias and the value can be set by the network manager. I would recommend you and, obviously if you can manage it, to put your desired types in this field."

I understand you mean I must configure previously some label in the interface (for example via telnet/ssh to the device and the appropiate command to change the label). That specific label musts reflect the type of traffic the interface carries out. This label will be read by snmpcollector in the ifAlias field.... If you mean that then it's a not valid approach because thet network is maintained by other people and this label use to be different between the zone, it doesn't  have a standarized format. But yes, I agree it would be the best option.

Let me know if I've understood you well.

Thanks again and BR,

Jes

**Comment by sbengo** [comment]
Hi @jjess ,

As you said, the first approach needs you to configure ifAlias directly on devices, it is a pity that you cannot mange it!

You can try then the second approach, I'm not sure it will work as expected but I think it can fit your usecase! Remember that to mantain your filters you will only have to change overriden varcatalog values on each device instead of changing OID Conditions pattterns and Meas Filters!

I would like to keep this issue open if you are going to try it! Let me know if you have some plans to do it!

Thanks,
Regards!

**Comment by jjess** [comment]
Ok sbengo. Thanks. I'll give it a try. Let me some time to think about how to deploy it. 

BR,

Jes

**Comment by jjess** [comment]
Hi again:

I'm trying the first approach, with the MULTISTRINGPARSER but not all the interfaces for every device are being monitorized or their metrics stored in influxdb. Description below with screenshots.

I have several interface to monitorize in every device. As an example, for one device I should monitorize the interfaces named as Eth-Trunk100, Eth-Trunk110.1, Eth-Trunk110.2, Eth-Trunk110.951, Eth-Trunk110.952, Eth-Trunk110.953, Eth-Trunk110.954, so I have this OIDs:

![imagen](https://user-images.githubusercontent.com/902573/86456319-2bd2e280-bd22-11ea-9328-7549022631fb.png)

The measurement_group is named "traffic". In this measurement_group a new MULTISTRINGPARSER metric is included:

![imagen](https://user-images.githubusercontent.com/902573/86458709-faf4ac80-bd25-11ea-86b3-fc3f08bb682e.png)

![imagen](https://user-images.githubusercontent.com/902573/86458749-09db5f00-bd26-11ea-8395-6898b00984a7.png)


This MULSTRINGPARSER is configured to generate a field named "info" and a tag named "traffictype".

And the device has this measurement filters:

![imagen](https://user-images.githubusercontent.com/902573/86458789-1f508900-bd26-11ea-8a31-3047629575fa.png)


The problem now is that despite of this device has several interface, included in the measurement_filters, everyone with an ifAlias with a format matching the MULSTRINGPARSER metric (xxxx_yyyy_zzzz), only metrics for the first interface, Eth-Trunk100, are being collected. The rest of interfaces seems to be ignored as they doesn't appear in influxdb. 

I cannot figure out where is the error. Any idea?

Thanks in advance,

Jes

**Comment by jjess** [comment]
Maybe instead of several measurement_groups for every interface, shoul I create a multi OID with all the interfaces that must be included? It would be a multi OID very big....

**Comment by jjess** [comment]
What I'm guessing regarding the logs and what interfaces are being monitorized for every device is that the only interfaces aht are being monitorized are those that appear in first place in the measurement_filters:

![imagen](https://user-images.githubusercontent.com/902573/86463286-7c037200-bd2d-11ea-85e5-a59525977e47.png)


With my previous approach, as I had several measurements groups it seems as the first measurement_group applied only to the first measurement_filter, the second measurement_group applied only to the second measurement_filter, and so on. This worked but with excessive snmp load for the equipments.

I'm not sure if I'm right or not.

Bye

**Comment by sbengo** [comment]
Hi @jjess , thanks for the detailed explanation

First of all, would you please contact me by email? (it is on my profile)

Regarding about your use case, I'm a bit lost: why do you need to filter interfaces?

The original issue is about getting extra tags by each interface and, setting up on a MULTISTRINGPARSER should be enough. I mean, if an interface doesn't match with your MULTISTRINGPARSER regex it won't generate your tag/field, so it would be sent as null values.

In case that you really need to filter interfaces on each device, I would recommend you to create a OID Condition by each device, setting up in your match expression all desired interfaces:

Example:
```
1.3.6.1.2.1.31.1.1.1.1 - OID Condition - ^Eth-Trunk100$|^Eth-Trunk110.1$|^Eth-Trunk110.2$|^Eth-Trunk110.951$
```

Your proposal would do N times the same OID query and applied on the same measurement. As you said, only the first Filter would match and it would ignores the rest of them. To apply several conditions on the same measurement, and only if you really need it, you can do it using an extra OID Conditions with `IsMultiple` enabled and the OR/AND logical expression

Thanks,
Regards!

**Comment by sbengo** [comment]
@jjess , I'm closing this issue, I think you managed to tag your interfaces :)
Feel free to re-open if you have more questions!

Thanks,
Regards!
