### ISSUE TITLE
[Question] Is it possible to match only part of the OID as base?

### ISSUE THREAD

**Issue by hoosee** [toni-moreno/snmpcollector#432]
Hi!

Thought to ask before banging my head too much against the wall.

I have a situation where I have one OID location for the names:

```
# snmpwalk <options> 1.3.6.1.4.1.14179.2.2.1.1.3
AIRESPACE-WIRELESS-MIB::bsnAPName.'../.:.' = STRING: "AP1"
AIRESPACE-WIRELESS-MIB::bsnAPName.'..c.. ' = STRING: "AP2"

```
But the measurements themselves contain AP-name + radio identifier so I cannot directly map them together.

```
# snmpwalk <options> 1.3.6.1.4.1.14179.2.2.13.1.1
AIRESPACE-WIRELESS-MIB::bsnAPIfLoadRxUtilization.'../.:.'.0 = INTEGER: 0
AIRESPACE-WIRELESS-MIB::bsnAPIfLoadRxUtilization.'../.:.'.1 = INTEGER: 0
AIRESPACE-WIRELESS-MIB::bsnAPIfLoadRxUtilization.'..c.. '.0 = INTEGER: 0
AIRESPACE-WIRELESS-MIB::bsnAPIfLoadRxUtilization.'..c.. '.1 = INTEGER: 0

```
Is it possible to somehow process this using multistring parser so that I could break this into two parts, the base OID + radio tag?

**Comment by sbengo** [comment]
Hi @hoosee , sorry for the late answer

I'm afraid that currently is not possible to get base OID and append another value on metrics based on parth of the OID. The measurement OID and the metric must match

Thanks,
Regards

**Comment by toni-moreno** [comment]
Hello @hoosee  @sbengo have developed two new measurement indexing mode with flexible way to merge different tables. Could you please review if you can do now what you need ?

**Comment by sbengo** [comment]
Hi @hoosee , it is actually possible using the new `Multi Index` measurements.
We don't have any device, so I would ask you to send us the following report in order to validate the proposal (c&p directly from issue template):

```
# git clone https://github.com/etingof/snmpsim.git`
# cd snmpsim
# sudo python3 setup.py install
# mkdir sim_data
# snmpsim-record-commands --protocol-version 2c --community <your_comunity> --agent-udpv4-endpoint=<your_device>:161 --output-file=./sim_data/device_data
# tar zcvf sim_data_<DATE>_#<issue>.tar.gz sim_data
```

So, what you can do is the following:
*Please note that on the following approach, the dimension of APName index is just 1, if there are more `dots . ` on the index of APName you should reflect them on the _Index 1_ dependency and the TagFormat to parse the index

Define a new measurement with mode MultiIndex
_Index 0_
In the first index we will retrieve the tag: APName, so it will be a simple: `Indexed with Direct Tag` index:
```
Index Label: AP Name MultiIndex
Index Description:Index to retrieve MultiIndex
Index Base OID: .1.3.6.1.4.1.14179.2.2.1.1.3
Index Tag: APName
Index Tag Format: 
Index Dependency:
```
![image](https://user-images.githubusercontent.com/13196237/110423712-da91a480-80a1-11eb-8d81-dc0c9fbabebc.png)


The output of this index will be, using your example and supposing the dimension of the index is 1 (no dots on it)
```
.1.3.6.1.4.1.14179.2.2.1.1.3
[.1]: "AP1"
[.2]: "AP2"
```

_Index 1_

The second index can be directly a `Indexed with Direct Tag` index with base OID of a metric, but we will need to heridate the tag based on the first index, as the index dimension is 2 (on this example):

```
Index Label: bsnAPIfLoadRxUtilization
Index Description: bsnAPIfLoadRxUtilization
Index Base OID: 1.3.6.1.4.1.14179.2.2.13.1.1
Index Tag: bsnAPIfSlotId
Index Tag Format: ${IDX1|DOT[1:1]|}
Index Dependency: IDX{0};DOT[0:0];SKIP
```
![image](https://user-images.githubusercontent.com/13196237/110423737-e41b0c80-80a1-11eb-9b2b-80d544bb6744.png)

The index dependency is the field to heridate tags based on some match.
As the _Index 1_ output has part of the index of IDX0, we will use it to heridate those tags, as an example

```
.1.3.6.1.4.1.14179.2.2.13.1.1
[.1.0]: "APName: AP1| bsnAPIifSlotID: 0" 
[.1.1]: "APName: AP1| bsnAPIifSlotID: 1"
[.2.0]: "APName: AP2| bsnAPIifSlotID: 0"
[.2.1]: "APName: AP2| bsnAPIifSlotID: 1"
```

_Result_
On the Result field of the measurement, we can use it directly the output of the IDX1, as all metrics needs the same index than defined on _Index 1_

```
Multi Index Result: IDX{1}
```

![image](https://user-images.githubusercontent.com/13196237/110423766-f301bf00-80a1-11eb-8125-b9ae711ddc98.png)

Try the propsal and give us feedback!

I'm closing this issue since it can be done
