### ISSUE TITLE
[Feature Request] Possible to fetch only one oid per request

### ISSUE THREAD

**Issue by dBitech** [toni-moreno/snmpcollector#435]
When you create a new SNMP device, SNMPcollector tries to query by sending 5 oids in a single request. 
```
{ SNMPv2c C="read" { GetRequest(84) R=-1750039157  system.sysDescr.0 system.sysUpTime.0 system.sysContact.0 system.sysName.0 system.sysLocation.0 } }
```
I have a device with an embedded SNMP agent, this device is very simple and as a result, it only supports one oid per snmpget.  

Would it be possible to add an option on a per device instance simular to concurrent gather that would allow for this?

**Comment by sbengo** [comment]
Hi @dBitech 

I can give you the following suggestion and see if it can solve your issue, please, give us some feedback!

1. Set up Alternate System OIDs:

There are some devices types (like squids), that the basis system OIDs differs from MIB-2, so we had to add a custom field called `Alternate System OID's` to allow the user set up custom OIDs to check device connectivity

I suggest you to set up a single OID, for example:

Alternate System OID's: `sysUpTime=.1.3.6.1.2.1.1.3.0`

![image](https://user-images.githubusercontent.com/13196237/86788429-74620700-c066-11ea-8a6e-d23b632feab8.png)

You can check it on `Test connection` button and it will appear your custom OID as device response:

![image](https://user-images.githubusercontent.com/13196237/86788566-9a87a700-c066-11ea-946d-03a63e99e468.png)

2. Disable Bulk

In order to allow only one GET at once, you can set up the field `DisableBulk: true` to disable GETBULK operations

Thanks,
Regards

**Comment by dBitech** [comment]
Thank you for this, but it's not quite the issues I'm seeing.

The issue shows up when the test connection is tried. the initial snmpget() tries to retrieve more than 1 initial oid in a single PDU  regardless of the setting of MaxRepetitions, DisableBulk, ConcurrentGather

https://github.com/toni-moreno/snmpcollector/issues/378  may also be related,

**Comment by sbengo** [comment]
Hi @dBitech , thanks for the answer.

Just before digging into it, did you try to set only 1 initial OID on `Alternate System OID's`?

Example: `Alternate System OID's: sysUpTime=.1.3.6.1.2.1.1.3.0`

Thanks,
Regards

**Comment by dBitech** [comment]
Yes, 

![image](https://user-images.githubusercontent.com/10306894/86850085-855e4880-c065-11ea-8c1d-5136f6698e4c.png)


tcp dump shows: ``` { SNMPv2c C="read" { GetRequest(84) R=1345045270  system.sysDescr.0 system.sysUpTime.0 system.sysContact.0 system.sysName.0 system.sysLocation.0 } }```

**Comment by sbengo** [comment]
Thanks for the info

Quite strange, in code the OID map passed to client is just the Alternate OID config

Just to verify, and sorry:

- Did you reload config after device changes?
- Could you please share the content of file: `logs/snmpdebug_xx.xxx.xxx.xx_init.log`?

Thanks,
Regards!

**Comment by dBitech** [comment]
I stook up a new instance today to test this further, this solution using the Alternate OID config appears to be working correctly.  We can close this issue.

Thank you for the assitance
