### ISSUE TITLE
[Bug] 0.8.1 not compatible with 0.8.0

### ISSUE THREAD

**Issue by MisterBaz** [toni-moreno/snmpcollector#447]
Using Docker version of snmpcollector.  I've had a good running instance of 0.8.0 for some time.  I tried upgrading to 0.8.1 today.  Yeah, no way is it compatible with 0.8.0.  Not even close.  I also got the same issue I had with persistent volumes as I did with 0.8.0.

I even tried spinning up a new instance all by itself, no previous files - I couldn't import any of my templates or even add a server.  I kept getting the snmpcollector "attempt to write a readonly database" error.

I ended up just reverting back to 0.8.0.  Everything back to working like it was before 0.8.1.

**Comment by toni-moreno** [comment]
@MisterBaz. Yes , I'm sorry I forgot document about one important change on the docker image from 0.8.0 to 0.8.1 . snmpcollector won't never run as "root" user inside the docker container. in order to migrate to 0.8.1 you should previously change the ownership to UID=472 GID=472 on all your volumes.

Could you test migrate again please?

Thank you very much

**Comment by toni-moreno** [comment]
Added doc in the wiki with this upgrade change  in the docker image (https://github.com/toni-moreno/snmpcollector/wiki#installation-and-setup)
