### ISSUE TITLE
[Question] Is it possible to somehow manipulate index oid like it can be done in "Index Tag Format" 

### ISSUE THREAD

**Issue by ciberp** [toni-moreno/snmpcollector#456]
What SnmpCollector version are you using?
Version: 0.8.1, Commit: 2ce0d07, Build Date: 2020/10/14 07:41:11

What OS are you running snmpcollector on?
CentOS Linux release 7.8.2003 (Core)

What did you do?
From cpmCoreXmin I get oid index "1000.0" or "1000.1" and I would like to strip ".x" and get only "1000". So I can do lookup in entPhysicalName and get CPU name. Is there any other way to achieve that?

![image](https://user-images.githubusercontent.com/23559198/98375447-663aec00-2042-11eb-995c-b6246d500f60.png)
![image](https://user-images.githubusercontent.com/23559198/98375551-89659b80-2042-11eb-81da-4557ce346c8a.png)
![image](https://user-images.githubusercontent.com/23559198/98377153-bca92a00-2044-11eb-81f6-31356488968a.png)
![image](https://user-images.githubusercontent.com/23559198/98376977-8a97c800-2044-11eb-9be8-59e26143efa5.png)

If I do that for cpmCPUTotal5secRev I get proper oid index "1000" and lookup in entPhysicalName returns CPU name.

![image](https://user-images.githubusercontent.com/23559198/98373810-165b2580-2040-11eb-932c-80c0a161e525.png)
![image](https://user-images.githubusercontent.com/23559198/98373874-2a9f2280-2040-11eb-990e-4c1b4f35167c.png)
![image](https://user-images.githubusercontent.com/23559198/98372012-65ec2200-203d-11eb-9bca-6347c6de568b.png)
![image](https://user-images.githubusercontent.com/23559198/98373967-4efaff00-2040-11eb-941b-64df41039d64.png)

snmpwalk for cpmCorePhysicalIndex (1.3.6.1.4.1.9.9.109.1.1.2.1.2):
```
CISCO-PROCESS-MIB::cpmCorePhysicalIndex.1000.0 = INTEGER: 0
CISCO-PROCESS-MIB::cpmCorePhysicalIndex.1000.1 = INTEGER: 0
```
snmpwalk for cpmCPUTotalPhysicalIndex  (.1.3.6.1.4.1.9.9.109.1.1.1.1.2):
`CISCO-PROCESS-MIB::cpmCPUTotalPhysicalIndex.1000 = INTEGER: 1000`

snmpwalk for entPhysicalName (.1.3.6.1.2.1.47.1.1.1.1.7):
```
ENTITY-MIB::entPhysicalName.1000 = STRING: Supervisor(slot 1)
ENTITY-MIB::entPhysicalName.1001 = STRING: Port Container 1/1
...
```
Thank you for your answers.
Best regards,
Peter

**Comment by sbengo** [comment]
Hi @ciberp , thanks for the detailed explanation

As you have said, actually there is no way to get only a part of index or a custom builtin one

I'm not sure but I think you are trying to mix different tables.
In CISCO-PROCESS-MIB, there are 2 tables to report the CPU:

- `1.3.6.1.4.1.9.9.109.1.1.2.1.2 | cpmCoreEntry` : provides information of different cores, by core and entity
- `.1.3.6.1.4.1.9.9.109.1.1.1.1.2 | cpmCPUTotalEntry`: provides infromation of all cores, by entity

The `1.3.6.1.4.1.9.9.109.1.1.1.1.2` returns de value of the entity mapped on ENTITY-MIB and it can match with the `totalCPU` metrics (your defined are from this table)

For those cases that the Tag is not directly on the same table that is being queries by metrics, we have the `Indirect Tag` mode in measurement definition.

We have described the way to retrieve those metrics on the following example: https://github.com/toni-moreno/snmpcollector/wiki/Example:-Configuring-Cisco-Catalyst-Switch#23-cisco-cpu-measurement

Take a look and give us some feedback!

Thanks,
Regards!

**Comment by ciberp** [comment]
Hi! @sbengo , thank you for your quick response and explanation. Sorry for the long delay, but I could not managed to test sooner.

I gave up on old Cisco 4500X and I give it a try on newest Cisco ASR1002-HX. I started with `cpmCore` and encountered the same problem as on 4500X, then I checked `cpmCPUTotal` as it was working fine on 4500X and found out that lookup in `entPhysical` is not right. So with ASR I have now problem with name/description lookup on both `cpmCPUTotal` and `cpmCore`.

![image](https://user-images.githubusercontent.com/23559198/99076337-42842280-25bb-11eb-982c-3f0c2ff18147.png)
![image](https://user-images.githubusercontent.com/23559198/99076380-56c81f80-25bb-11eb-980c-47a2e45c65a8.png)
![image](https://user-images.githubusercontent.com/23559198/99076471-795a3880-25bb-11eb-810c-ef3ce14d0833.png)
Index for `cpmCPUTotal` is .7 and this is working OK, but index for `entPhysicalName/Descr` should be .7051 and not .7 as it is now:
![image](https://user-images.githubusercontent.com/23559198/99076657-c50ce200-25bb-11eb-94f2-7983137506d0.png)

This can be seen in snmpwalk (.1.3.6.1.4.1.9.9.109.1.1.1.1):
```
CISCO-PROCESS-MIB::cpmCPUTotalPhysicalIndex.7 = INTEGER: 7051
CISCO-PROCESS-MIB::cpmCPUTotal5sec.7 = Gauge32: 0
CISCO-PROCESS-MIB::cpmCPUTotal1min.7 = Gauge32: 1
CISCO-PROCESS-MIB::cpmCPUTotal5min.7 = Gauge32: 1
CISCO-PROCESS-MIB::cpmCPUTotal5secRev.7 = Gauge32: 0 percent
CISCO-PROCESS-MIB::cpmCPUTotal1minRev.7 = Gauge32: 1 percent
CISCO-PROCESS-MIB::cpmCPUTotal5minRev.7 = Gauge32: 1 percent
CISCO-PROCESS-MIB::cpmCPUMonInterval.7 = Gauge32: 0 seconds
```
and snmpwalk for entPhysicalName (.1.3.6.1.2.1.47.1.1.1.1.7)
```
ENTITY-MIB::entPhysicalName.1 = STRING: Chassis
ENTITY-MIB::entPhysicalName.2 = STRING: Power Supply Bay 0
ENTITY-MIB::entPhysicalName.3 = STRING: Power Supply Module 0
ENTITY-MIB::entPhysicalName.4 = STRING: Vin  P0/0
ENTITY-MIB::entPhysicalName.5 = STRING: Iin  P0/1
ENTITY-MIB::entPhysicalName.6 = STRING: Vout P0/2
ENTITY-MIB::entPhysicalName.7 = STRING: Iout P0/3
...
ENTITY-MIB::entPhysicalName.7051 = STRING: cpu R0/0
```
It looks like this value `CISCO-PROCESS-MIB::cpmCPUTotalPhysicalIndex.7 = INTEGER: 7051` should be used as index somehow and then I could do right lookup in `entPhysicalName`. I tried both direct and indirect _GetMode_ but with no succes since both use the same index. To solve this problem I would need two different index-es one for `entPhysicalName` and one for `cpmCPUTotal`. I guess this can't be done in one table?

Thank you for your answers.
Best regards,
Peter

**Comment by ciberp** [comment]
Hi! I also checked another even newer box Cisco9500, it has the same approach as ASR:
```
CISCO-PROCESS-MIB::cpmCPUTotalPhysicalIndex.4 = INTEGER: 1041
CISCO-PROCESS-MIB::cpmCPUTotal5sec.4 = Gauge32: 0
CISCO-PROCESS-MIB::cpmCPUTotal1min.4 = Gauge32: 1
CISCO-PROCESS-MIB::cpmCPUTotal5min.4 = Gauge32: 1
CISCO-PROCESS-MIB::cpmCPUTotal5secRev.4 = Gauge32: 0 percent
CISCO-PROCESS-MIB::cpmCPUTotal1minRev.4 = Gauge32: 1 percent
CISCO-PROCESS-MIB::cpmCPUTotal5minRev.4 = Gauge32: 1 percent
```
```
ENTITY-MIB::entPhysicalName.1 = STRING: Chassis
ENTITY-MIB::entPhysicalName.2 = STRING: Power Supply Bay 0
ENTITY-MIB::entPhysicalName.3 = STRING: Power Supply Bay 1
ENTITY-MIB::entPhysicalName.4 = STRING: Cisco Catalyst 9500 Series Fan 
...
ENTITY-MIB::entPhysicalName.1041 = STRING: Switch 1 - CPU
```
Best regards,
Peter

**Comment by sbengo** [comment]
As always, thanks for the detailed explanation!
First of all, as you have seen, you are trying to retrieve the `CPUTotal` not the `cpmCore`.

We are working to improve our wiki, but I think you have missed the behaviour of measurement core parameter `GetMode`. Let me explain you how it works:

The idea of SNMPCollector Measurement entity is that the IndexOID should retrieve at least a pair of [index]:[TagValue] in order to match the metrics and ensure that each metric can be identified by its name.
The SNMPCollector covers the most common cases and it is related with measurement `GetMode`:

### A: (SNMP Table) Direct Index ==> The metrics are on the same "Table" than the TagValue and indexes are shared
In this case, the `GetMode` is `Indexed with direct Tag`. As an example:

Measurement:
```
Index OID: .1.2.3.4
Walk over IndexOID:
.1.2.3.4[.1] = "eth1"
.1.2.3.4[.2] = "eth2"
.1.2.3.4[.3] = "eth3"
```
Metrics:
```
Base OID: 1.2.3.5
Walk over BaseOID:
.1.2.3.5[.1] = 33
.1.2.3.5[.2] = 41
.1.2.3.5[.3] = 52
```

So the pair [index]:[tagValue] of the measurement will match the metrics:
Final Metric:
```
.1.2.3.5[.1] = 33 | eth1
.1.2.3.5[.2] = 41 | eth2
.1.2.3.5[.3] = 52 | eth3
```


### B: (SNMP Table) Indexed with indirect tag ==> The TagValue is on another table but there is an IndexOID that gives you that index and, the IndexOID shares the same indexes with metrics

Measurement:
```
Index OID: .1.2.3.4
Walk over IndexOID:
.1.2.3.4[.1] = 90
.1.2.3.4[.2] = 91
.1.2.3.4[.3] = 92
```
The value of [90, 91, 92] are the the index of another table that gives us the TagValue:

```
Ta:gOID: .1.2.3.5:
Walk over TagOID:
.1.2.3.5[.90] = "eth1"
.1.2.3.5[.91] = "eth2"
.1.2.3.5[.92] = "eth3"
```

The measurement defined as Indirect Tag will generate the pair [index]:[TagValue] as the Index of IndexOID and the value of the result of the TagOID, so:
```
[.1] = "eth1"
[.2] = "eth2"
[.3] = "eth3"
```
And the final result over the metrics will be the same as the case above


---

### Cisco CPM Total
On your Cisco case, as it is explained on the example, the OID  - `cpmCPUTotalPhysicalIndex: .1.3.6.1.4.1.9.9.109.1.1.1.1.2` - gives you as value the index to retrieve the tag name, so **you need to define the measurement as `GetMode`: indiret tag and the TagOID as `entPhysicalName: 1.3.6.1.2.1.47.1.1.1.1.7`**

In this case, the measurement behaviour will:

Measurement
```
IndexOID: 
Index OID:  .1.3.6.1.4.1.9.9.109.1.1.1.1.2
Walk over IndexOID:
.1.3.6.1.4.1.9.9.109.1.1.1.1.2[.7] = 7051

TagOID: 1.3.6.1.2.1.47.1.1.1.1.7
Walk over TagOID:
1.3.6.1.2.1.47.1.1.1.1.7[.7051] = "cpu R0/0"
```

So the final pair of [index]:[tagvalue] will be `[.7] = "cpuR0/0"` and it will match with your metrics, allowing them to be identified by the name of the cpu!!

Check that your measurement definition is the same as exposed on wiki:

https://github.com/toni-moreno/snmpcollector/wiki/Example:-Configuring-Cisco-Catalyst-Switch#23-cisco-cpu-measurement

If you have some doubts, check the Cisco Doc, referenced on wiki: https://github.com/toni-moreno/snmpcollector/wiki/Example:-Configuring-Cisco-Catalyst-Switch#02-select-metrics-to-collect-data

Thanks,
Regards!

**Comment by ciberp** [comment]
Hi! @sbengo thank you for your quick response and detailed explanation. I obviously read the wiki poorly ... I followed your detailed instructions and now It works as expected. Thank you for your time.

![image](https://user-images.githubusercontent.com/23559198/99232113-ccb5cc00-27f1-11eb-81d5-68f85f231bc8.png)
![image](https://user-images.githubusercontent.com/23559198/99232040-b0199400-27f1-11eb-80fd-348013d144b7.png)
![image](https://user-images.githubusercontent.com/23559198/99232237-f4a52f80-27f1-11eb-808f-fcf6a956537e.png)

And for individual cores I use:
![image](https://user-images.githubusercontent.com/23559198/99232562-5a91b700-27f2-11eb-9f6c-c08c89a7a0a2.png)
![image](https://user-images.githubusercontent.com/23559198/99232620-6f6e4a80-27f2-11eb-9e89-3dc65cf03044.png)
![image](https://user-images.githubusercontent.com/23559198/99232709-9167cd00-27f2-11eb-98b5-54a3be39bebf.png)
4500x:
![image](https://user-images.githubusercontent.com/23559198/99232808-ad6b6e80-27f2-11eb-9cf1-72b74a71b98e.png)

Best regards,
Peter
