### ISSUE TITLE
[Question] Limit Log Sizes?  How to edit Retention Policy?

### ISSUE THREAD

**Issue by sbazzell** [toni-moreno/snmpcollector#465]
Running SNMPCOLLECTOR as a docker container.  It consistently will just continue to write to the log files for each SNMP device.  This starts to consume all disk space on the linux host.

Within the SNMPCOLLECTOR Web UI, there is a single section that talks about the retention policy, but just states it must exist on the database.  Where in the world do I edit the retention policy?  Can this be a docker environment variable?

**Comment by toni-moreno** [comment]
Hello @sbazzell , sorry for the big delay in the response ,in order to save disk space for logs , we recommend config all your devices in "error" mode , export the log path into a external path with named or bind volume and also add rotatelog configuration if needed in your host. 

Policy retencion only refers to the policy retencion configured in your influxDB backend, nothing to do with log size.

I will close this issue , please reopen it if needed.
